# Generated by Django 5.0.3 on 2024-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='unit',
            field=models.CharField(default='Hour', max_length=20),
        ),
    ]
