# Generated by Django 5.0.3 on 2024-04-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0007_remove_service_rate_serviceprovider_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='profession',
            new_name='servicename',
        ),
    ]
