# Generated by Django 5.0.3 on 2024-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0008_rename_profession_serviceprovider_servicename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='servicename',
            new_name='Profession',
        ),
    ]
