# Generated by Django 5.0.3 on 2024-04-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0009_rename_servicename_serviceprovider_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='availability',
            field=models.CharField(default='Available', max_length=100),
        ),
    ]
