# Generated by Django 5.0.3 on 2024-05-01 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0010_serviceprovider_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='servicedate',
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
