# Generated by Django 5.0.3 on 2024-05-02 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0012_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='landmark',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='homeowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hmsapp.homeowner'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hmsapp.serviceprovider'),
        ),
    ]
