# Generated by Django 5.0.3 on 2024-05-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0014_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='servicetime',
        ),
    ]
