# Generated by Django 5.0.3 on 2024-05-02 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0015_rename_booking_time_booking_servicetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='jobdescription',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
