# Generated by Django 5.0.3 on 2024-05-02 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0019_rename_profession_serviceprovider_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
