# Generated by Django 5.0.3 on 2024-05-04 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0021_alter_booking_jobdescription_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='update',
            name='user',
        ),
        migrations.AddField(
            model_name='billing',
            name='homeowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.homeowner'),
        ),
        migrations.AddField(
            model_name='billing',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.serviceprovider'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='homeowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.homeowner'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.serviceprovider'),
        ),
        migrations.AddField(
            model_name='payment',
            name='homeowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.homeowner'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.serviceprovider'),
        ),
        migrations.AddField(
            model_name='update',
            name='homeowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.homeowner'),
        ),
        migrations.AddField(
            model_name='update',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hmsapp.serviceprovider'),
        ),
    ]
