# Generated by Django 5.0.3 on 2024-05-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0022_remove_cancellation_user_remove_update_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellation',
            name='cancellation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
