# Generated by Django 5.0.3 on 2024-05-04 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0023_alter_cancellation_cancellation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='update_date',
            new_name='updatemade_date',
        ),
        migrations.AddField(
            model_name='update',
            name='updateto_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
