# Generated by Django 5.0.3 on 2024-05-04 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0024_rename_update_date_update_updatemade_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='updateto_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
