# Generated by Django 5.0.3 on 2024-05-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0025_update_updateto_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isupdated',
            field=models.TextField(default='No'),
        ),
    ]
