# Generated by Django 5.0.3 on 2024-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0026_booking_isupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalrate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
