# Generated by Django 5.0.3 on 2024-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0030_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='israted',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Bill created', 'Bill created'), ('Paid', 'Paid'), ('Finished', 'Finished')], default='Pending', max_length=20),
        ),
    ]
