# Generated by Django 5.0.3 on 2024-05-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0031_booking_israted_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.booking'),
        ),
    ]
