# Generated by Django 5.0.3 on 2024-05-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0032_alter_reviews_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.booking'),
        ),
    ]
