# Generated by Django 5.0.3 on 2024-06-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0035_alter_payment_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='eligible',
            field=models.CharField(default='Yes', max_length=20),
        ),
    ]
