# Generated by Django 5.0.3 on 2024-06-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0036_serviceprovider_eligible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='eligible',
            field=models.CharField(default='No', max_length=20),
        ),
    ]
