# Generated by Django 5.0.3 on 2024-06-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0037_alter_serviceprovider_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='has_new_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='new_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
