# Generated by Django 5.0.3 on 2024-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0038_serviceprovider_has_new_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='bill_images/'),
        ),
    ]
