# Generated by Django 5.0.3 on 2024-06-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0041_alter_billing_bill_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='bill_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
