# Generated by Django 5.0.3 on 2024-11-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0043_alter_billing_bill_image_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitereview',
            fields=[
                ('sitereview_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('review', models.TextField()),
            ],
        ),
    ]
